/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package resume.parser;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    public void test() {
        System.out.println("this is a test of the test source folder for resume-parser");
    }
}
